import type { AffectionBlock, Character, Scene, StatBlock } from './types'

export const gameTitle = '星海未寄'
export const chapterTitle = '第一章：雨后的空教室'

export const initialStats: StatBlock = {
  courage: 0,
  inspiration: 0,
  trust: 0,
}

export const initialAffection: AffectionBlock = {
  haruka: 0,
  mio: 0,
  rinka: 0,
}

export const themeSong = '/assets/music/hoshiumi-theme.mp3'

export const characters: Character[] = [
  {
    id: 'narrator',
    name: '旁白',
    role: '叙事',
    description: '只描述可见的细节：雨、信纸、琴键、粉笔和选择后的微小变化。',
  },
  {
    id: 'yuto',
    name: '青井悠斗',
    role: '玩家角色',
    description: '高二转校生，擅长写短篇小说。害怕被人遗忘，却在转校第一天收到一封未来寄来的情书。',
  },
  {
    id: 'haruka',
    name: '白咲遥',
    role: '学生会书记',
    portrait: '/assets/characters/shirasaki-haruka.png',
    description: '冷静、礼貌、记录欲极强。她的手账里提前写着悠斗还没说出口的话。',
  },
  {
    id: 'mio',
    name: '七濑澪',
    role: '轻音部主唱',
    portrait: '/assets/characters/nanase-mio.png',
    description: '用玩笑掩饰不安的主唱。她唱的是恋歌，每一句都像告别。',
  },
  {
    id: 'rinka',
    name: '九条凛花',
    role: '美术部王牌',
    portrait: '/assets/characters/kujo-rinka.png',
    description: '直接、尖锐、讨厌多余社交。她画下的不是未来，而是别人忘掉的过去。',
  },
]

export const scenes: Record<string, Scene> = {
  schoolGate: {
    id: 'schoolGate',
    name: '雨后的校门',
    time: '周一 07:48',
    subtitle: '鞋柜里有一封没有被雨打湿的信。',
    background: '/assets/backgrounds/school-gate-rain.png',
    bgm: '/assets/bgm/morning-after-rain.mp3',
    bgmName: '雨后初见',
    goal: '拆开匿名信，决定第一天如何面对异常。',
    cast: ['haruka'],
    dialogue: [
      {
        id: 'sg-01',
        speaker: '旁白',
        characterId: 'narrator',
        text: '鞋柜里躺着一封淡蓝色的信。雨水没有沾湿它，像有人刚刚放进去。',
        audio: '/assets/voice/sg-01.mp3',
      },
      {
        id: 'sg-02',
        speaker: '青井悠斗',
        characterId: 'yuto',
        text: '转校第一天收到信，这种展开只会出现在三流恋爱小说里吧。',
        audio: '/assets/voice/sg-02.mp3',
      },
      {
        id: 'sg-03',
        speaker: '白咲遥',
        characterId: 'haruka',
        mood: 'calm',
        position: 'center',
        text: '青井同学，早上好。你迟到了三分钟。',
        audio: '/assets/voice/sg-03.mp3',
      },
      {
        id: 'sg-04',
        speaker: '青井悠斗',
        characterId: 'yuto',
        text: '我们……见过？',
        audio: '/assets/voice/sg-04.mp3',
      },
      {
        id: 'sg-05',
        speaker: '白咲遥',
        characterId: 'haruka',
        mood: 'guarded',
        position: 'center',
        text: '没有。至少今天以前，没有。',
        audio: '/assets/voice/sg-05.mp3',
      },
    ],
    videoEventAfterDialogue: {
      id: 'letter-first-rain',
      title: '第一封信',
      text: '信纸在鞋柜里轻轻颤动，像从还没发生的明天寄来。',
      src: '/assets/video/letter-first-rain.mp4',
      poster: '/assets/backgrounds/school-gate-rain.png',
      messageAfter: '第一封信没有署名。你必须决定，是相信遥，还是先把异常藏起来。',
    },
    choices: [
      {
        id: 'ask-haruka',
        text: '先问遥是否知道这封信',
        description: '她会把你写进手账，也会把自己的动摇藏起来。',
        affectionDelta: { haruka: 2 },
        statDelta: { trust: 1 },
        flag: 'askedHarukaLetter',
        nextScene: 'classroom',
      },
      {
        id: 'hide-letter',
        text: '把信收进口袋，假装没看见',
        description: '你选择先观察。灵感提升，但遥会察觉你在隐瞒。',
        affectionDelta: { rinka: 1 },
        statDelta: { inspiration: 1 },
        flag: 'letterHidden',
        nextScene: 'classroom',
      },
    ],
  },
  classroom: {
    id: 'classroom',
    name: '二年 B 班',
    time: '周一 08:12',
    subtitle: '明亮的教室里，每个人都像知道你会来。',
    background: '/assets/backgrounds/classroom-morning.png',
    bgm: '/assets/bgm/new-classroom.mp3',
    bgmName: '新班级的光',
    goal: '在日常里寻找第一封信的作者。',
    cast: ['haruka', 'mio'],
    dialogue: [
      {
        id: 'cl-01',
        speaker: '七濑澪',
        characterId: 'mio',
        mood: 'playful',
        position: 'left',
        text: '新同学，要不要选靠窗的位置？那边很适合忧郁男主角。',
        audio: '/assets/voice/cl-01.mp3',
      },
      {
        id: 'cl-02',
        speaker: '青井悠斗',
        characterId: 'yuto',
        text: '我看起来像那种人吗？',
        audio: '/assets/voice/cl-02.mp3',
      },
      {
        id: 'cl-03',
        speaker: '七濑澪',
        characterId: 'mio',
        mood: 'smile',
        position: 'left',
        text: '不像。所以才要从座位开始培养气质。',
        audio: '/assets/voice/cl-03.mp3',
      },
      {
        id: 'cl-04',
        speaker: '白咲遥',
        characterId: 'haruka',
        mood: 'strict',
        position: 'right',
        text: '七濑同学，上课前请把吉他拨片收起来。',
        audio: '/assets/voice/cl-04.mp3',
      },
      {
        id: 'cl-05',
        speaker: '七濑澪',
        characterId: 'mio',
        mood: 'teasing',
        position: 'left',
        text: '书记大人连别人的心跳都要登记吗？',
        audio: '/assets/voice/cl-05.mp3',
      },
    ],
    choices: [
      {
        id: 'sit-near-mio',
        text: '坐到澪旁边',
        description: '她会把一张没有署名的曲谱塞给你。',
        affectionDelta: { mio: 2 },
        statDelta: { inspiration: 1 },
        flag: 'mioSeatRoute',
        nextScene: 'musicRoom',
      },
      {
        id: 'watch-haruka-notebook',
        text: '注意遥的手账',
        description: '你发现手账里提前写着刚才的选择。',
        affectionDelta: { haruka: 1 },
        statDelta: { inspiration: 1, trust: 1 },
        flag: 'noticedHarukaNotebook',
        nextScene: 'musicRoom',
      },
    ],
  },
  musicRoom: {
    id: 'musicRoom',
    name: '放学后的音乐教室',
    time: '周一 16:42',
    subtitle: '未完成的歌在夕阳里断了一拍。',
    background: '/assets/backgrounds/music-room-sunset.png',
    bgm: '/assets/bgm/unfinished-love-song.mp3',
    bgmName: '未完成的告白曲',
    goal: '听完澪的歌，确认匿名信不是普通情书。',
    cast: ['mio', 'rinka'],
    dialogue: [
      {
        id: 'mr-01',
        speaker: '七濑澪',
        characterId: 'mio',
        mood: 'soft',
        position: 'center',
        text: '偷听要收费哦。新同学的话，第一分钟免费。',
        audio: '/assets/voice/mr-01.mp3',
      },
      {
        id: 'mr-02',
        speaker: '青井悠斗',
        characterId: 'yuto',
        text: '这首曲子叫什么？',
        audio: '/assets/voice/mr-02.mp3',
      },
      {
        id: 'mr-03',
        speaker: '七濑澪',
        characterId: 'mio',
        mood: 'sad-smile',
        position: 'center',
        text: '还没有名字。因为写它的人还没想起来。',
        audio: '/assets/voice/mr-03.mp3',
      },
      {
        id: 'mr-04',
        speaker: '九条凛花',
        characterId: 'rinka',
        mood: 'sharp',
        position: 'right',
        text: '别被她的歌骗了。第一封信不是告白，是求救。',
        audio: '/assets/voice/mr-04.mp3',
      },
    ],
    videoEventAfterDialogue: {
      id: 'mio-first-song',
      title: '未完成的告白曲',
      text: '夕阳掠过琴键，澪回头时，未写完的旋律像一封迟到的信。',
      src: '/assets/video/mio-first-song.mp4',
      poster: '/assets/backgrounds/music-room-sunset.png',
      messageAfter: '最后一个音落下时，黑板上出现一句话：不要相信第一封信。',
    },
    choices: [
      {
        id: 'listen-mio-song',
        text: '留下听完这首歌',
        description: '触发澪的夕阳演出。最后一个音落下时，黑板上会出现新的警告。',
        affectionDelta: { mio: 2 },
        statDelta: { inspiration: 2 },
        flag: 'heardMioSong',
        nextScene: 'nightClassroom',
      },
      {
        id: 'follow-rinka-warning',
        text: '追问凛花为什么说是求救',
        description: '凛花会带你看烧剩的未来信。',
        affectionDelta: { rinka: 2, mio: -1 },
        statDelta: { courage: 2 },
        flag: 'trustedRinkaWarning',
        nextScene: 'nightClassroom',
      },
    ],
  },
  nightClassroom: {
    id: 'nightClassroom',
    name: '夜晚的空教室',
    time: '周一 19:06',
    subtitle: '窗玻璃上映出四个人影。',
    background: '/assets/backgrounds/empty-classroom-night.png',
    bgm: '/assets/bgm/seventh-letter.mp3',
    bgmName: '第七封信',
    goal: '选择第二章路线。今晚之后，会有一个人忘记你。',
    cast: ['haruka', 'mio', 'rinka'],
    dialogue: [
      {
        id: 'nc-01',
        speaker: '旁白',
        characterId: 'narrator',
        text: '教室的灯忽然熄灭。窗玻璃上映出四个人影。',
        audio: '/assets/voice/nc-01.mp3',
      },
      {
        id: 'nc-02',
        speaker: '白咲遥',
        characterId: 'haruka',
        mood: 'urgent',
        position: 'left',
        text: '第一封信不是我写的。但我知道第二封在哪里。',
        audio: '/assets/voice/nc-02.mp3',
      },
      {
        id: 'nc-03',
        speaker: '七濑澪',
        characterId: 'mio',
        mood: 'fragile',
        position: 'center',
        text: '悠斗，别露出那种表情。我会想起不该想起的事。',
        audio: '/assets/voice/nc-03.mp3',
      },
      {
        id: 'nc-04',
        speaker: '九条凛花',
        characterId: 'rinka',
        mood: 'direct',
        position: 'right',
        text: '选择吧。今晚之后，我们三个人里会有一个人忘记你。',
        audio: '/assets/voice/nc-04.mp3',
      },
      {
        id: 'nc-05',
        speaker: '青井悠斗',
        characterId: 'yuto',
        text: '如果这是恋爱游戏，为什么每个选项都像告别？',
        audio: '/assets/voice/nc-05.mp3',
      },
    ],
    videoEventAfterDialogue: {
      id: 'seventh-letter-classroom',
      title: '第七封信',
      text: '夜色压住教室，粉笔灰浮起，三个人的影子同时映在窗上。',
      src: '/assets/video/seventh-letter-classroom.mp4',
      poster: '/assets/backgrounds/empty-classroom-night.png',
      messageAfter: '今晚之后，你选择的人会记住你；另一个人会把你忘掉。',
    },
    choices: [
      {
        id: 'route-haruka',
        text: '跟遥去学生会室核对手账',
        description: '第二章会从遥路线开局：手账里的未来记录。',
        affectionDelta: { haruka: 2 },
        statDelta: { trust: 1 },
        routeSeed: 'haruka',
        ending: true,
      },
      {
        id: 'route-mio',
        text: '跟澪去天台听完整首歌',
        description: '第二章会从澪路线开局：被删除的旋律。',
        affectionDelta: { mio: 2 },
        statDelta: { inspiration: 1 },
        routeSeed: 'mio',
        ending: true,
      },
      {
        id: 'route-rinka',
        text: '跟凛花去焚烧炉找信灰',
        description: '第二章会从凛花路线开局：画中烧毁的过去。',
        affectionDelta: { rinka: 2 },
        statDelta: { courage: 1 },
        routeSeed: 'rinka',
        ending: true,
      },
    ],
  },
}

export const endingDialogue = [
  {
    id: 'ed-01',
    speaker: '旁白',
    characterId: 'narrator',
    text: '黑板上，粉笔自己写下最后一行字：第七封信，明天寄出。',
    audio: '/assets/voice/ed-01.mp3',
  },
  {
    id: 'ed-02',
    speaker: '青井悠斗',
    characterId: 'yuto',
    text: '我不知道自己选的是谁。只知道从这一刻开始，日常再也回不去了。',
    audio: '/assets/voice/ed-02.mp3',
  },
] satisfies Scene['dialogue']

export const sceneOrder = ['schoolGate', 'classroom', 'musicRoom', 'nightClassroom'] as const
